# Generated by Django 3.0.7 on 2020-06-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='image',
            field=models.ImageField(blank=True, height_field=100, upload_to='welcome/images/', width_field=100),
        ),
    ]
