# Generated by Django 3.0.7 on 2020-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20200625_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='image',
            field=models.ImageField(blank=True, upload_to='welcome/images/'),
        ),
    ]
