# Generated by Django 3.0.7 on 2020-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('emailId', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=100)),
                ('loggedIn', models.BooleanField()),
            ],
        ),
    ]
